[db]
password = "${SUPABASE_DB_PASSWORD}"

project_id = "qvxrcjpvoieboiykflnv"

[auth]
enabled = true
site_url = "https://simplr-invoice-flow.lovable.app/"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits"
jwt_secret = ""

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 300
